language: python

cache: pip

python:
    - "2.7"
    - "pypy"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

install:
  - pip install tox-travis
script:
  - tox

notifications:
  on_success: never
  on_failure: always
